name: fda_logger
description: The logger approach for feature driven architecture.
version: 0.0.3
publish_to: none

environment:
  sdk: ^3.3.2

dependencies:
  fda_di:
    git:
      url: https://github.com/Blago-Development/fda.git
      path: packages/fda_di
      ref: di_0.0.3
  logger: ^2.3.0

dev_dependencies:
  blg_linter:
    git:
      url: https://github.com/Blago-Development/blg_linter.git
      ref: 1.0.0
