name: fda
description: The feature driven architecture package.
version: 0.0.1
repository: https://github.com/Blago-Development/fda
publish_to: none

environment:
  sdk: ^3.3.2

dependencies:
  fda_arch:
    git:
      url: https://github.com/Blago-Development/fda.git
      path: packages/fda_arch
      ref: arch_0.0.1
  fda_di:
    git:
      url: https://github.com/Blago-Development/fda.git
      path: packages/fda_di
      ref: di_0.0.2

dev_dependencies:
  blg_linter:
    git:
      url: https://github.com/Blago-Development/blg_linter.git
      ref: 1.0.0
