name: fda
description: The feature driven architecture package.
version: 0.0.5
repository: https://github.com/Blago-Development/fda
publish_to: none

environment:
  sdk: ^3.3.2

dependencies:
  fda_di:
    git:
      url: https://github.com/Blago-Development/fda.git
      path: packages/fda_di
      ref: di_0.0.2
  fda_exceptions:
    git:
      url: https://github.com/Blago-Development/fda.git
      path: packages/fda_exceptions
      ref: exceptions_0.0.3
  fda_logger:
    git:
      url: https://github.com/Blago-Development/fda.git
      path: packages/fda_logger
      ref: logger_0.0.2
  fda_tools:
    git:
      url: https://github.com/Blago-Development/fda.git
      path: packages/fda_tools
      ref: tools_0.0.1

dev_dependencies:
  blg_linter:
    git:
      url: https://github.com/Blago-Development/blg_linter.git
      ref: 1.0.0
