name: fda_tools
description: Tools for feature driven architecture.
version: 0.0.1

environment:
  sdk: ^3.3.2

dev_dependencies:
  blg_linter:
    git:
      url: https://github.com/Blago-Development/blg_linter.git
      ref: 1.0.0
